apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-task
spec:
  description: This Task can be used to run a Maven build only for token deployment.
  params:
    - default: .
      description: The context directory within the repository for sources on which we want to execute maven goals.
      name: CONTEXT_DIR
      type: string
    - default: 'registry.access.redhat.com/ubi8/openjdk-17:1.17-1.1696520325'
      description: Maven base image
      name: MAVEN_IMAGE
      type: string
    - default:
        - package
      description: maven goals to run
      name: GOALS
      type: array
  results:
    - description: application version used for image tag
      name: app-version
      type: string
  steps:
    - computeResources: {}
      image: 'registry.redhat.io/ubi8/ubi-minimal:8.10'
      name: mvn-settings
      script: |
        #!/usr/bin/env bash
        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \
        echo 'using existing $(workspaces.maven-settings.path)/settings.xml' && exit 0
        cat > $(workspaces.maven-settings.path)/settings.xml
    - args:
        - '-s'
        - $(workspaces.maven-settings.path)/settings.xml
        - '-Dmaven.repo.local=$(workspaces.maven-cache.path)'
        - $(params.GOALS)
      command:
        - /usr/bin/mvn
      computeResources:
        limits:
          cpu: '2'
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 500Mi
      image: $(params.MAVEN_IMAGE)
      name: mvn-goals
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source
    - description: The workspace consisting of the custom maven settings provided by the user.
      name: maven-settings
    - name: maven-cache
